use_frameworks!

source 'https://github.com/lihongcheng996/AYBoys.git'


platform :ios, '8.0'

target 'AYBoysKit_Example' do
  pod 'AYBoysKit', :path => '../'

  target 'AYBoysKit_Tests' do
    inherit! :search_paths

    
  end
end
